<div class="checkout-onepage-payment-additional-giftcardaccount">
<p class="note">
    <?php $_url = Mage::getUrl('checkout/cart'); ?>
    <?php echo Mage::helper('icube_giftcardaccount')->__('To add or remove gift cards, <a href="%s">click here</a>.', $_url); ?><br />

    <?php if ((float)$this->getAppliedGiftCardAmount()): ?>
        <?php $amount = Mage::helper('core')->currency($this->getAppliedGiftCardAmount(), true); ?>
        <?php echo Mage::helper('icube_giftcardaccount')->__('Gift Card amount applied to order: %s', $amount); ?>
    <?php endif; ?>
</p>
</div>
