<?php /* @var $this Mage_Adminhtml_Block_Catalog_Product_Composite_Fieldset_Qty */ ?>

<div class="giftcard-qty-form">
    <ul class="form-list">
        <li class="fields">
            <div class="field">
                <label><?php echo $this->__('Quantity'); ?></label>
                <div class="input-box">
                    <input id="product_composite_configure_input_qty" class="input-text" type="text" name="qty" value="<?php echo $this->getQtyValue() * 1 ?>">
                </div>
            </div>
        </li>
    </ul>
</div>
