<div class="entry-edit">
    <?php echo $this->getFormHtml() ?>
<?php /*if( $form->getUseContainer() === true ): ?>
<form id="<?php echo $form->getFormId() ?>" method="<?php echo ( $form->getFormMethod() ) ? $form->getFormMethod() : 'post' ; ?>" action="<?php echo $form->getFormAction() ?>" <?php echo ( $form->getFormEnctype() ) ? 'enctype="' . $this->getForm()->getFormEnctype() . '"' : '' ?> >
<?php endif; ?>
    <?php foreach ($form->getElements() as $_element): ?>
    <?php echo $this->drawElement($_element) ?>
    <?php endforeach; ?>
<?php if( $form->getUseContainer() === true ): ?>
</form>
<?php endif;*/ ?>
</div>
<script type="text/javascript">
//<![CDATA[
    Event.observe(window, 'load', updateCurrency);
    Event.observe($('_infowebsite_id'), 'change', updateCurrency);

    var currencies = <?php echo $this->getCurrencyJson(); ?>;

    function updateCurrency()
    {
        val = $('_infowebsite_id').options[$('_infowebsite_id').selectedIndex].value;
        if (currencies[val]) {
            $('balance_currency').innerHTML = '<b>[' + currencies[val] + ']</b>';
        }
    }
//]]>
</script>
