<input type="hidden" name="creditmemo[refund_giftcardaccount]" value="0">
<?php if ($this->canRefundToCustomerBalance()): ?>
    <p>
        <label for="creditmemo_refund_giftcardaccount"><?php echo Mage::helper('icube_giftcardaccount')->__('Refund Gift Cards to Store Credit') ?></label>
        <input type="checkbox" name="creditmemo[refund_giftcardaccount]" value="1" id="creditmemo_refund_giftcardaccount">
    </p>
<?php endif; ?>
