<?php
/**
 * @see Icube_GiftCardAccount_Block_Checkout_Cart_Giftcardaccount
 */
?>
<?php if(Mage::getSingleton('customer/session')->isLoggedIn()) : ?>
<div class="giftcard">
    <h2><?php echo $this->__('Gift Cards') ?></h2>
    <div id="giftcard_balance_lookup"></div>
    <span id="gc-please-wait" class="please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Please wait, loading...') ?>
    </span>
    <form id="giftcard-form" action="<?php echo $this->getUrl('icube_giftcardaccount/cart/redeem') ?>" method="post">
        <fieldset>
            <div class="input-box">
                <input class="required-entry input-text" id="giftcard_code" name="giftcard_code" value="" />
            </div>
            <div class="buttons-set">
                <button class="button" onclick="giftcardForm.submit()" type="button" value="<?php echo $this->__('Redeem') ?>"><span><span><?php echo $this->__('Redeem') ?></span></span></button>
                <button class="button check-gc-status" onclick="checkGiftCardStatus();" type="button" value="<?php echo $this->__('Check balance') ?>"><span><span><?php echo $this->__('Check balance') ?></span></span></button>
            </div>
        </fieldset>
    </form>

    <script type="text/javascript">
    //<![CDATA[
    var giftcardForm = new VarienForm('giftcard-form');
    function checkGiftCardStatus()
    {
        if (giftcardForm.validator && !giftcardForm.validator.validate()) {
            return false;
        }
        new Ajax.Updater(
            'giftcard_balance_lookup',
            '<?php echo Mage::getUrl('icube_giftcardaccount/cart/quickCheck') ?>',
            {
                onCreate: function() { $('gc-please-wait').show(); },
                onComplete: function() { $('gc-please-wait').hide(); },
                parameters : {giftcard_code : $('giftcard_code').value}
            }
        );
    }
    //]]>
    </script>
</div>
<?php endif; ?>